Tamil = int(input("Enter the Tamil Mark:"))
English = int(input("Enter the English Mark:"))
Maths = int(input("Enter the Maths Mark:"))
Computer = int(input("Enter the Computer Mark:"))
Social = int(input("Enter the Social Mark:"))
print("Tamil mark is:",Tamil)
print("English mark is:",English)
print("Maths mark is:",Maths)
print("Computer mark is:",Computer)
print("Social mark is:",Social)