team1_name = input("Enter Team 1 name:")
team1_score = int(input("Enter Team 1 score:"))
team1_overs = int(input("Enter Team 1 overs played:"))
team2_name = input("Enter Tean 2 name:")
team2_score = int(input("Enter Team 2 score:"))
team2_overs = int(input("Enter Team 2 overs played:"))
print("Match Details:")
print("Team 1:")
print("Name:",team1_name)
print("Score:",team1_score)
print("Overs played:",team1_overs)
print("Team 2:")
print("Name:",team2_name)
print("Score:",team2_score)
print("Overs played:",team2_overs)